name: Philler-Challenge-Addons # Replace with your own plugin name. You can use the MUtils namespace to highlight the connection
load: STARTUP
version: 1.0.2 # Replace with your own plugin version. Should rise on updates
main: de.dasphiller.challengeAddon.MAddon # Replace your new main class (after changing namespace)
api-version: 1.16
authors: [ xPhiller ] # Replace with your name
description: MUtils Challenge Addon - Adds some nice Challenges to MChallenge! # Replace with your fancy description
website: https://mutils.net/
softdepend: [ MUtils-Challenge ] # IMPORTANT - Keep this to load MChallenge before your plugin